import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useSession, signIn, signOut } from "next-auth/react";

const Home: NextPage = () => {
  const { data: session } = useSession();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        {session && (
          <>
            Signed in as {JSON.stringify(session)} <br />
            <button onClick={() => signOut()}>Sign out</button>
          </>
        )}

        {!session && (
          <>
            Not signed in <br />
            <button onClick={() => signIn("line")}> LINEでログイン</button>
            <button onClick={() => signIn("apple")}> Appleでログイン</button>
            <button onClick={() => signIn("google")}> Googleでログイン</button>
            <label htmlFor={"email"}>メールアドレアドレス</label>
            <input type={"text"} />
          </>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
